version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
    ".github/**",
    "dist/**",
    "examples/**",
    "lang/**",
    "vendors/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = ["nodejs"]
  style_guide = "airbnb"